# ArgoCD Application for TheDrive - Simple GitOps Configuration
#
# SIMPLE APPROACH:
# - ArgoCD uses values.yaml from GitHub (no secrets)
# - Uses existing thedrive-secrets that Helm already created
# - No manual secret creation needed!
#
# GitOps Workflow:
# 1. You change values.yaml in GitHub
# 2. ArgoCD detects changes and deploys automatically
# 3. Uses existing secrets from your Helm deployment

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thedrive-app
  namespace: argocd
  labels:
    app: thedrive
spec:
  project: default
  
  source:
    repoURL: https://github.com/destinyobs/CCDriveAPI.git
    targetRevision: main
    path: helm/thedrive
    
    helm:
      valueFiles:
      - values.yaml
      # No need for parameters - just use values.yaml + existing secrets
  
  destination:
    server: https://kubernetes.default.svc
    namespace: thedrive
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
# That's it! 
# 
# Your existing Helm deployment already created:
# - thedrive-secrets (contains your passwords)
# - All the resources in thedrive namespace
# 
# ArgoCD will now:
# 1. Read values.yaml from GitHub (safe, no secrets)
# 2. Use existing thedrive-secrets from your Helm deployment
# 3. Keep everything in sync automatically
#
# To deploy: kubectl apply -f thedrive-application.yaml
