apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thedrive.fullname" . }}-db-init
  labels:
    {{- include "thedrive.labels" . | nindent 4 }}
data:
  init-db.sql: |
    -- TheDrive API Database Initialization Script
    -- This script creates the main database for the TheDrive API

    -- Create the database if it doesn't exist
    IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'TheDriveAPI')
    BEGIN
        CREATE DATABASE [TheDriveAPI];
        PRINT 'Database TheDriveAPI created successfully';
    END
    ELSE
    BEGIN
        PRINT 'Database TheDriveAPI already exists';
    END
    GO

    -- Switch to the TheDriveAPI database
    USE [TheDriveAPI];
    GO

    -- Grant permissions to SA user (already has sysadmin but being explicit)
    -- Note: In production, you should create a dedicated database user
    PRINT 'Database initialization completed';
    GO
