# Secret Template
# This template creates a Kubernetes Secret to store sensitive configuration data
#
# Security Features:
# - All values are automatically base64 encoded by Helm
# - Data is encrypted at rest in etcd (if cluster encryption is enabled)
# - Can be mounted as files or environment variables in pods
# - Separate from ConfigMap to maintain security boundaries
#
# Key Management:
# - Database passwords and connection strings
# - API keys for external services (SendGrid, S3)
# - JWT signing secrets for authentication
# - All sensitive data that should not be in plain text

apiVersion: v1
kind: Secret
metadata:
  # Secret name using Helm template function for consistent naming
  name: {{ include "thedrive.fullname" . }}-secrets
  labels:
    # Standard Helm labels for resource management
    {{- include "thedrive.labels" . | nindent 4 }}
type: Opaque
data:
  # Database authentication
  # SA password for SQL Server authentication
  sa-password: {{ .Values.database.auth.saPassword | b64enc | quote }}
  
  # Complete database connection string with embedded password
  # This approach ensures proper password substitution at template time
  # Format: Server=host,port;Database=name;User Id=user;Password=pass;Options
  connection-string: {{ printf "Server=%s-mssql-service,1433;Database=%s;User Id=sa;Password=%s;TrustServerCertificate=True;MultipleActiveResultSets=true;" (include "thedrive.fullname" .) .Values.api.env.dbName .Values.database.auth.saPassword | b64enc | quote }}
  
  # JWT authentication secret for token signing and validation
  # Should be a long, random string for security
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  
  # SendGrid API key for email services (password reset, notifications)
  # Obtain from SendGrid dashboard after account setup
  sendgrid-api-key: {{ .Values.secrets.sendgridApiKey | b64enc | quote }}
  
  # S3 secret key for object storage authentication
  # Used with S3 access key for file upload/download operations
  s3-secret-key: {{ .Values.secrets.s3SecretKey | b64enc | quote }}
