# Service: Provides load balancing and external access to API pods
# This allows people outside the cluster to access your API
# It also load balances between multiple API pods

apiVersion: v1
kind: Service
metadata:
  name: thedrive-api-service
  namespace: thedrive
  labels:
    app: thedrive-api
spec:
  type: NodePort            # Makes the service accessible from outside the cluster
                            # NodePort exposes the service on each node's IP at a static port
  ports:
  - port: 80                # Port for internal cluster communication
    targetPort: 5256        # Port that your API containers are listening on
    nodePort: 30256         # External port (must be between 30000-32767)
                            # People can access your API at: your-server-ip:30256
    protocol: TCP
    name: http
  selector:
    app: thedrive-api       # Route traffic to pods with this label
                            # K8s will automatically load balance between all matching pods
---
